---
settings:
  id_local: 1
  seuil_temperature_min: 10
  seuil_temperature_max: 30
  seuil_humidite_min: 40
  seuil_humidite_max: 70
  compteur: 5
  interval_secondes: 30

database:
  host: 192.168.1.21
  port: 3306
  user: Gestionnaire
  password: Password123
  database: gestionstock

email:
  sender: sender@mail.com
  password: '*********'
  destinations:
    - dest@mail.com
  server_addr: smtp.gmail.com
  server_port: 587
